"use client";

import { useState, useEffect, useMemo } from "react";

type Question = {
  id: string;
  category: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

type CandidateInfo = {
  candidateName: string;
  candidateEmail: string;
  companyName: string;
  recruiterEmail: string;
  role: string;
};

const categories = [
  { id: "fundamentals", name: "AI Fundamentals", description: "Core concepts and terminology" },
  { id: "llms", name: "LLM Knowledge", description: "Large language models and prompting" },
  { id: "practical", name: "Practical Application", description: "Real-world implementation" },
  { id: "ethics", name: "Ethics & Safety", description: "Responsible AI use" },
  { id: "tools", name: "Tools & Ecosystem", description: "AI tools and platforms" },
];

const questions: Question[] = [
  // AI Fundamentals
  {
    id: "f1",
    category: "fundamentals",
    question: "What is the primary difference between supervised and unsupervised learning?",
    options: [
      "Supervised learning is faster than unsupervised learning",
      "Supervised learning uses labeled data, unsupervised learning finds patterns in unlabeled data",
      "Unsupervised learning requires more computational power",
      "Supervised learning only works with images",
    ],
    correctIndex: 1,
    explanation: "Supervised learning trains on labeled examples (input-output pairs), while unsupervised learning discovers patterns in data without predefined labels.",
  },
  {
    id: "f2",
    category: "fundamentals",
    question: "What does 'hallucination' mean in the context of AI language models?",
    options: [
      "The model experiencing a software bug",
      "The model generating confident but factually incorrect information",
      "The model refusing to answer questions",
      "The model running out of memory",
    ],
    correctIndex: 1,
    explanation: "Hallucination refers to when AI models generate plausible-sounding but factually incorrect or nonsensical information with apparent confidence.",
  },
  {
    id: "f3",
    category: "fundamentals",
    question: "What is a 'token' in the context of language models?",
    options: [
      "A security credential for API access",
      "A unit of text (word, subword, or character) that the model processes",
      "A type of neural network layer",
      "A payment unit for AI services",
    ],
    correctIndex: 1,
    explanation: "Tokens are the basic units that language models process - typically words, parts of words, or characters depending on the tokenization method.",
  },
  {
    id: "f4",
    category: "fundamentals",
    question: "What is 'fine-tuning' in machine learning?",
    options: [
      "Adjusting the learning rate during training",
      "Taking a pre-trained model and training it further on specific data",
      "Removing bugs from the model code",
      "Compressing the model for faster inference",
    ],
    correctIndex: 1,
    explanation: "Fine-tuning involves taking a model pre-trained on general data and continuing its training on a smaller, task-specific dataset to improve performance on that task.",
  },

  // LLM Knowledge
  {
    id: "l1",
    category: "llms",
    question: "Which prompting technique involves giving the model examples before asking it to perform a task?",
    options: [
      "Zero-shot prompting",
      "Chain-of-thought prompting",
      "Few-shot prompting",
      "Recursive prompting",
    ],
    correctIndex: 2,
    explanation: "Few-shot prompting provides the model with a few examples of the desired input-output format before presenting the actual task, helping it understand the expected response pattern.",
  },
  {
    id: "l2",
    category: "llms",
    question: "What is the 'context window' of a language model?",
    options: [
      "The user interface for interacting with the model",
      "The maximum amount of text the model can process in a single request",
      "The time limit for generating responses",
      "The memory used to store the model weights",
    ],
    correctIndex: 1,
    explanation: "The context window is the maximum number of tokens (input + output) that a language model can handle in a single interaction, affecting how much information it can consider.",
  },
  {
    id: "l3",
    category: "llms",
    question: "What is 'temperature' when configuring an LLM?",
    options: [
      "The physical heat generated by the server",
      "A parameter controlling the randomness/creativity of outputs",
      "The speed of response generation",
      "The cost per token",
    ],
    correctIndex: 1,
    explanation: "Temperature controls output randomness - lower values (e.g., 0) make outputs more deterministic and focused, while higher values increase creativity and variability.",
  },
  {
    id: "l4",
    category: "llms",
    question: "What is RAG (Retrieval-Augmented Generation)?",
    options: [
      "A technique to make models run faster",
      "Combining LLMs with external knowledge retrieval to ground responses in specific data",
      "A method to reduce model size",
      "A type of image generation model",
    ],
    correctIndex: 1,
    explanation: "RAG enhances LLM responses by first retrieving relevant information from external sources (databases, documents) and including it in the prompt, reducing hallucinations and enabling access to current/specific information.",
  },

  // Practical Application
  {
    id: "p1",
    category: "practical",
    question: "A customer service team wants to use AI to handle inquiries. What's the most important first step?",
    options: [
      "Immediately deploy the most advanced AI model available",
      "Replace all human agents with AI",
      "Analyze current inquiries to identify which are suitable for AI automation",
      "Build a custom model from scratch",
    ],
    correctIndex: 2,
    explanation: "Understanding the current workload helps identify high-volume, repetitive inquiries suitable for AI while preserving human handling for complex or sensitive cases.",
  },
  {
    id: "p2",
    category: "practical",
    question: "You're implementing an AI system and it's producing occasional errors. What's the best approach?",
    options: [
      "Disable the system until it's perfect",
      "Ignore errors if they're infrequent",
      "Implement human-in-the-loop review for uncertain cases and feedback mechanisms",
      "Add more training data until errors stop",
    ],
    correctIndex: 2,
    explanation: "Human-in-the-loop systems allow AI to handle confident cases while escalating uncertain ones for human review, and feedback mechanisms enable continuous improvement.",
  },
  {
    id: "p3",
    category: "practical",
    question: "When would you recommend NOT using AI for a business task?",
    options: [
      "When the task requires consistent, repeatable outputs",
      "When decisions require human judgment, empathy, or carry significant consequences",
      "When the task involves processing large amounts of data",
      "When the task is time-consuming for humans",
    ],
    correctIndex: 1,
    explanation: "AI should augment, not replace, human judgment in high-stakes decisions. Tasks requiring empathy, ethical judgment, or where errors have serious consequences often need human oversight.",
  },
  {
    id: "p4",
    category: "practical",
    question: "What's the main advantage of using an API-based AI service vs. training your own model?",
    options: [
      "API services are always more accurate",
      "API services are always cheaper",
      "Faster deployment, no ML expertise needed, maintained by provider",
      "API services never have usage limits",
    ],
    correctIndex: 2,
    explanation: "API-based services allow rapid deployment without requiring ML expertise or infrastructure, with the provider handling updates and maintenance. Custom models may be better for specialized needs or data privacy requirements.",
  },

  // Ethics & Safety
  {
    id: "e1",
    category: "ethics",
    question: "What is 'prompt injection' and why is it a concern?",
    options: [
      "A technique to make prompts more effective",
      "Malicious input designed to manipulate an AI system into ignoring instructions or revealing information",
      "Adding variables to prompts programmatically",
      "A method to speed up model responses",
    ],
    correctIndex: 1,
    explanation: "Prompt injection attacks attempt to override system instructions by embedding malicious commands in user input, potentially causing the AI to leak sensitive information or behave unexpectedly.",
  },
  {
    id: "e2",
    category: "ethics",
    question: "When using AI to process personal data, what should be a primary consideration?",
    options: [
      "Ensuring the AI produces the fastest possible results",
      "Compliance with data privacy regulations and user consent",
      "Using the most advanced model available",
      "Minimizing computational costs",
    ],
    correctIndex: 1,
    explanation: "Processing personal data with AI requires careful attention to privacy regulations (GDPR, CCPA, etc.), informed consent, data minimization, and security measures.",
  },
  {
    id: "e3",
    category: "ethics",
    question: "What is 'AI bias' and how does it typically originate?",
    options: [
      "When AI systems have personal opinions",
      "Systematic errors in AI outputs often stemming from biased training data or design choices",
      "When AI is too slow to process requests",
      "When AI refuses to answer certain questions",
    ],
    correctIndex: 1,
    explanation: "AI bias refers to systematic unfair outputs, often originating from biased training data, unrepresentative samples, or design decisions that disadvantage certain groups.",
  },
  {
    id: "e4",
    category: "ethics",
    question: "What's the best practice for disclosing AI use to customers?",
    options: [
      "Never disclose AI use to avoid confusion",
      "Only disclose if legally required",
      "Be transparent about AI involvement, especially in customer-facing interactions",
      "Claim all AI outputs are from humans",
    ],
    correctIndex: 2,
    explanation: "Transparency about AI use builds trust, sets appropriate expectations, and is increasingly required by regulations. Users should know when they're interacting with AI systems.",
  },

  // Tools & Ecosystem
  {
    id: "t1",
    category: "tools",
    question: "What is the primary purpose of vector databases in AI applications?",
    options: [
      "Storing images and videos",
      "Storing and efficiently searching embeddings for semantic similarity",
      "Running machine learning training",
      "Managing user authentication",
    ],
    correctIndex: 1,
    explanation: "Vector databases store embeddings (numerical representations of data) and enable fast similarity search, crucial for RAG systems, semantic search, and recommendation engines.",
  },
  {
    id: "t2",
    category: "tools",
    question: "When would you choose Claude or GPT-4 over a smaller open-source model?",
    options: [
      "When cost is the primary concern",
      "When you need maximum control over the model",
      "When you need strong reasoning, broad knowledge, or instruction following without ML expertise",
      "When you have unlimited computational resources",
    ],
    correctIndex: 2,
    explanation: "Large commercial models excel at complex reasoning, broad knowledge tasks, and following nuanced instructions out-of-the-box, ideal when you lack ML expertise or need quick deployment.",
  },
  {
    id: "t3",
    category: "tools",
    question: "What is LangChain primarily used for?",
    options: [
      "Training new language models",
      "Building applications that chain together LLM calls, tools, and data sources",
      "Translating between programming languages",
      "Securing API endpoints",
    ],
    correctIndex: 1,
    explanation: "LangChain is a framework for building LLM-powered applications, providing tools for chaining prompts, integrating external data sources, and creating complex AI workflows.",
  },
  {
    id: "t4",
    category: "tools",
    question: "What's the benefit of using AI coding assistants like GitHub Copilot or Cursor?",
    options: [
      "They eliminate the need for code review",
      "They accelerate development by suggesting code, explaining errors, and automating repetitive tasks",
      "They guarantee bug-free code",
      "They replace the need to learn programming",
    ],
    correctIndex: 1,
    explanation: "AI coding assistants boost productivity by providing contextual suggestions, explaining code, and automating routine tasks, while still requiring human oversight and understanding.",
  },
];

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

function getProficiencyLevel(percentage: number): { level: string; color: string; description: string } {
  if (percentage >= 90) {
    return {
      level: "Expert",
      color: "text-terminal-green",
      description: "Demonstrates exceptional AI knowledge. Ready for advanced AI implementation roles.",
    };
  } else if (percentage >= 75) {
    return {
      level: "Advanced",
      color: "text-terminal-cyan",
      description: "Strong understanding of AI concepts and practical applications. Suitable for AI-integrated roles.",
    };
  } else if (percentage >= 60) {
    return {
      level: "Intermediate",
      color: "text-yellow-400",
      description: "Good foundational knowledge. Would benefit from hands-on AI experience.",
    };
  } else if (percentage >= 40) {
    return {
      level: "Basic",
      color: "text-orange-400",
      description: "Understands basic concepts but needs significant training for AI-related responsibilities.",
    };
  } else {
    return {
      level: "Novice",
      color: "text-red-400",
      description: "Limited AI knowledge. Requires comprehensive training before AI-related work.",
    };
  }
}

export default function Screening() {
  const [stage, setStage] = useState<"intro" | "info" | "quiz" | "results">("intro");
  const [candidateInfo, setCandidateInfo] = useState<CandidateInfo>({
    candidateName: "",
    candidateEmail: "",
    companyName: "",
    recruiterEmail: "",
    role: "",
  });
  const [shuffledQuestions, setShuffledQuestions] = useState<Question[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [timeRemaining, setTimeRemaining] = useState(20 * 60); // 20 minutes
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (stage === "quiz" && timeRemaining > 0) {
      const timer = setInterval(() => {
        setTimeRemaining((prev) => {
          if (prev <= 1) {
            clearInterval(timer);
            setStage("results");
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
      return () => clearInterval(timer);
    }
  }, [stage, timeRemaining]);

  const startQuiz = () => {
    setShuffledQuestions(shuffleArray(questions));
    setStage("quiz");
  };

  const handleAnswer = (questionId: string, optionIndex: number) => {
    setAnswers((prev) => ({ ...prev, [questionId]: optionIndex }));
  };

  const nextQuestion = () => {
    if (currentQuestion < shuffledQuestions.length - 1) {
      setCurrentQuestion((prev) => prev + 1);
    }
  };

  const prevQuestion = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion((prev) => prev - 1);
    }
  };

  const submitQuiz = async () => {
    setIsSubmitting(true);
    await new Promise((resolve) => setTimeout(resolve, 1500));
    setStage("results");
    setIsSubmitting(false);
  };

  const results = useMemo(() => {
    if (shuffledQuestions.length === 0) return null;

    const categoryScores: Record<string, { correct: number; total: number }> = {};
    let totalCorrect = 0;

    shuffledQuestions.forEach((q) => {
      if (!categoryScores[q.category]) {
        categoryScores[q.category] = { correct: 0, total: 0 };
      }
      categoryScores[q.category].total++;

      if (answers[q.id] === q.correctIndex) {
        categoryScores[q.category].correct++;
        totalCorrect++;
      }
    });

    const percentage = (totalCorrect / shuffledQuestions.length) * 100;
    const proficiency = getProficiencyLevel(percentage);

    return {
      totalCorrect,
      totalQuestions: shuffledQuestions.length,
      percentage,
      proficiency,
      categoryScores,
    };
  }, [shuffledQuestions, answers]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  const answeredCount = Object.keys(answers).length;

  // Intro stage
  if (stage === "intro") {
    return (
      <main className="min-h-screen bg-dark-900 py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <a href="/" className="font-mono text-xl font-bold text-terminal-green glow-green">
              hunsaker.ai
            </a>
            <h1 className="text-4xl md:text-5xl font-bold mt-8 mb-4">
              AI Proficiency <span className="text-terminal-green glow-green">Screening</span>
            </h1>
            <p className="text-xl text-gray-400 max-w-2xl mx-auto">
              Assess candidates' AI knowledge across fundamentals, practical application, and ethics.
            </p>
          </div>

          <div className="gradient-border rounded-lg bg-dark-800 p-8 mb-8">
            <h2 className="font-mono text-xl font-semibold text-terminal-cyan mb-6">// How It Works</h2>
            <div className="grid md:grid-cols-3 gap-6 mb-8">
              <div className="text-center">
                <div className="w-12 h-12 rounded-full bg-terminal-green/20 flex items-center justify-center mx-auto mb-3">
                  <span className="font-mono text-terminal-green font-bold">1</span>
                </div>
                <h3 className="font-semibold text-gray-200 mb-2">Enter Details</h3>
                <p className="text-gray-400 text-sm">Candidate and company information</p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 rounded-full bg-terminal-green/20 flex items-center justify-center mx-auto mb-3">
                  <span className="font-mono text-terminal-green font-bold">2</span>
                </div>
                <h3 className="font-semibold text-gray-200 mb-2">Take Assessment</h3>
                <p className="text-gray-400 text-sm">20 questions, 20 minutes</p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 rounded-full bg-terminal-green/20 flex items-center justify-center mx-auto mb-3">
                  <span className="font-mono text-terminal-green font-bold">3</span>
                </div>
                <h3 className="font-semibold text-gray-200 mb-2">Get Results</h3>
                <p className="text-gray-400 text-sm">Detailed proficiency report</p>
              </div>
            </div>

            <h3 className="font-mono text-terminal-cyan mb-4">// Categories Assessed</h3>
            <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-8">
              {categories.map((cat) => (
                <div key={cat.id} className="bg-dark-700 rounded-lg p-3 text-center">
                  <p className="text-gray-200 font-medium text-sm">{cat.name}</p>
                  <p className="text-gray-500 text-xs">{cat.description}</p>
                </div>
              ))}
            </div>

            <button
              onClick={() => setStage("info")}
              className="w-full py-4 bg-terminal-green text-dark-900 font-bold text-lg rounded-lg hover:bg-terminal-green/90 transition-colors"
            >
              Start Screening
            </button>
          </div>

          <p className="text-center text-gray-500 text-sm">
            Free tool by <a href="/" className="text-terminal-green hover:underline">hunsaker.ai</a>.
            Need custom AI assessments? <a href="/book" className="text-terminal-green hover:underline">Book a call</a>.
          </p>
        </div>
      </main>
    );
  }

  // Info collection stage
  if (stage === "info") {
    const canProceed = candidateInfo.candidateName && candidateInfo.candidateEmail;

    return (
      <main className="min-h-screen bg-dark-900 py-20 px-6">
        <div className="max-w-xl mx-auto">
          <div className="text-center mb-8">
            <a href="/" className="font-mono text-xl font-bold text-terminal-green glow-green">
              hunsaker.ai
            </a>
            <h1 className="text-3xl font-bold mt-8 mb-4">Candidate Information</h1>
            <p className="text-gray-400">Enter details before starting the assessment.</p>
          </div>

          <div className="gradient-border rounded-lg bg-dark-800 p-6">
            <div className="space-y-4">
              <div>
                <label className="block text-sm text-gray-400 mb-2">Candidate Name *</label>
                <input
                  type="text"
                  value={candidateInfo.candidateName}
                  onChange={(e) => setCandidateInfo((prev) => ({ ...prev, candidateName: e.target.value }))}
                  placeholder="Full name"
                  className="w-full px-4 py-3 bg-dark-700 border border-dark-600 rounded-lg text-gray-200 placeholder-gray-500 focus:border-terminal-green focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-sm text-gray-400 mb-2">Candidate Email *</label>
                <input
                  type="email"
                  value={candidateInfo.candidateEmail}
                  onChange={(e) => setCandidateInfo((prev) => ({ ...prev, candidateEmail: e.target.value }))}
                  placeholder="candidate@email.com"
                  className="w-full px-4 py-3 bg-dark-700 border border-dark-600 rounded-lg text-gray-200 placeholder-gray-500 focus:border-terminal-green focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-sm text-gray-400 mb-2">Company Name</label>
                <input
                  type="text"
                  value={candidateInfo.companyName}
                  onChange={(e) => setCandidateInfo((prev) => ({ ...prev, companyName: e.target.value }))}
                  placeholder="Hiring company"
                  className="w-full px-4 py-3 bg-dark-700 border border-dark-600 rounded-lg text-gray-200 placeholder-gray-500 focus:border-terminal-green focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-sm text-gray-400 mb-2">Recruiter/Hiring Manager Email</label>
                <input
                  type="email"
                  value={candidateInfo.recruiterEmail}
                  onChange={(e) => setCandidateInfo((prev) => ({ ...prev, recruiterEmail: e.target.value }))}
                  placeholder="recruiter@company.com"
                  className="w-full px-4 py-3 bg-dark-700 border border-dark-600 rounded-lg text-gray-200 placeholder-gray-500 focus:border-terminal-green focus:outline-none"
                />
                <p className="text-xs text-gray-500 mt-1">Results will be sent to this email</p>
              </div>
              <div>
                <label className="block text-sm text-gray-400 mb-2">Role Being Applied For</label>
                <input
                  type="text"
                  value={candidateInfo.role}
                  onChange={(e) => setCandidateInfo((prev) => ({ ...prev, role: e.target.value }))}
                  placeholder="e.g., Product Manager, Software Engineer"
                  className="w-full px-4 py-3 bg-dark-700 border border-dark-600 rounded-lg text-gray-200 placeholder-gray-500 focus:border-terminal-green focus:outline-none"
                />
              </div>
            </div>

            <div className="mt-8 p-4 bg-dark-700 rounded-lg">
              <h3 className="font-semibold text-gray-200 mb-2">Before You Start</h3>
              <ul className="text-sm text-gray-400 space-y-1">
                <li>• 20 multiple choice questions</li>
                <li>• 20 minute time limit</li>
                <li>• You can navigate between questions</li>
                <li>• Results are shown immediately after completion</li>
              </ul>
            </div>

            <button
              onClick={startQuiz}
              disabled={!canProceed}
              className={`w-full mt-6 py-4 font-bold text-lg rounded-lg transition-colors ${
                canProceed
                  ? "bg-terminal-green text-dark-900 hover:bg-terminal-green/90"
                  : "bg-gray-600 text-gray-400 cursor-not-allowed"
              }`}
            >
              Begin Assessment
            </button>
          </div>
        </div>
      </main>
    );
  }

  // Quiz stage
  if (stage === "quiz" && shuffledQuestions.length > 0) {
    const question = shuffledQuestions[currentQuestion];
    const category = categories.find((c) => c.id === question.category);

    return (
      <main className="min-h-screen bg-dark-900 py-20 px-6">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div>
              <span className="font-mono text-terminal-cyan text-sm">{category?.name}</span>
              <p className="text-gray-400 text-sm">
                Question {currentQuestion + 1} of {shuffledQuestions.length}
              </p>
            </div>
            <div className={`font-mono text-xl ${timeRemaining < 60 ? "text-red-400" : "text-terminal-green"}`}>
              {formatTime(timeRemaining)}
            </div>
          </div>

          {/* Progress bar */}
          <div className="h-2 bg-dark-700 rounded-full mb-8">
            <div
              className="h-full bg-terminal-green rounded-full transition-all duration-300"
              style={{ width: `${((currentQuestion + 1) / shuffledQuestions.length) * 100}%` }}
            />
          </div>

          {/* Question */}
          <div className="gradient-border rounded-lg bg-dark-800 p-6 mb-6">
            <h2 className="text-xl font-semibold text-gray-100 mb-6">{question.question}</h2>
            <div className="space-y-3">
              {question.options.map((option, index) => (
                <button
                  key={index}
                  onClick={() => handleAnswer(question.id, index)}
                  className={`w-full text-left px-4 py-3 rounded-lg transition-colors ${
                    answers[question.id] === index
                      ? "bg-terminal-green/20 border border-terminal-green text-terminal-green"
                      : "bg-dark-700 border border-dark-600 text-gray-300 hover:border-gray-500"
                  }`}
                >
                  <span className="font-mono text-terminal-cyan mr-3">
                    {String.fromCharCode(65 + index)}.
                  </span>
                  {option}
                </button>
              ))}
            </div>
          </div>

          {/* Navigation */}
          <div className="flex items-center justify-between">
            <button
              onClick={prevQuestion}
              disabled={currentQuestion === 0}
              className={`px-6 py-3 rounded-lg font-semibold transition-colors ${
                currentQuestion === 0
                  ? "text-gray-600 cursor-not-allowed"
                  : "text-terminal-green hover:bg-terminal-green/10"
              }`}
            >
              Previous
            </button>

            <span className="text-gray-500 text-sm">
              {answeredCount} of {shuffledQuestions.length} answered
            </span>

            {currentQuestion === shuffledQuestions.length - 1 ? (
              <button
                onClick={submitQuiz}
                disabled={isSubmitting}
                className="px-6 py-3 bg-terminal-green text-dark-900 font-semibold rounded-lg hover:bg-terminal-green/90 transition-colors disabled:opacity-50"
              >
                {isSubmitting ? "Submitting..." : "Submit"}
              </button>
            ) : (
              <button
                onClick={nextQuestion}
                className="px-6 py-3 bg-terminal-green text-dark-900 font-semibold rounded-lg hover:bg-terminal-green/90 transition-colors"
              >
                Next
              </button>
            )}
          </div>

          {/* Question navigator */}
          <div className="mt-8 p-4 bg-dark-800 rounded-lg">
            <p className="text-sm text-gray-400 mb-3">Question Navigator</p>
            <div className="flex flex-wrap gap-2">
              {shuffledQuestions.map((q, index) => (
                <button
                  key={q.id}
                  onClick={() => setCurrentQuestion(index)}
                  className={`w-8 h-8 rounded font-mono text-sm transition-colors ${
                    index === currentQuestion
                      ? "bg-terminal-green text-dark-900"
                      : answers[q.id] !== undefined
                      ? "bg-terminal-green/20 text-terminal-green"
                      : "bg-dark-700 text-gray-400 hover:bg-dark-600"
                  }`}
                >
                  {index + 1}
                </button>
              ))}
            </div>
          </div>
        </div>
      </main>
    );
  }

  // Results stage
  if (stage === "results" && results) {
    return (
      <main className="min-h-screen bg-dark-900 py-20 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-8">
            <a href="/" className="font-mono text-xl font-bold text-terminal-green glow-green">
              hunsaker.ai
            </a>
            <h1 className="text-3xl md:text-4xl font-bold mt-8 mb-4">Assessment Results</h1>
            <p className="text-gray-400">
              Results for <span className="text-gray-200">{candidateInfo.candidateName}</span>
              {candidateInfo.role && (
                <span> applying for <span className="text-gray-200">{candidateInfo.role}</span></span>
              )}
            </p>
          </div>

          {/* Overall Score */}
          <div className="gradient-border rounded-lg bg-dark-800 p-8 mb-8">
            <div className="text-center mb-6">
              <div className="font-mono text-6xl font-bold text-terminal-green mb-2">
                {results.percentage.toFixed(0)}%
              </div>
              <div className={`text-2xl font-semibold ${results.proficiency.color}`}>
                {results.proficiency.level}
              </div>
              <p className="text-gray-400 mt-2">
                {results.totalCorrect} of {results.totalQuestions} correct
              </p>
            </div>

            <div className="bg-dark-700 rounded-lg p-4">
              <p className="text-gray-300">{results.proficiency.description}</p>
            </div>
          </div>

          {/* Category Breakdown */}
          <div className="gradient-border rounded-lg bg-dark-800 p-6 mb-8">
            <h2 className="font-mono text-xl font-semibold text-terminal-cyan mb-6">// Score by Category</h2>
            <div className="space-y-4">
              {categories.map((cat) => {
                const score = results.categoryScores[cat.id];
                if (!score) return null;
                const percentage = (score.correct / score.total) * 100;

                return (
                  <div key={cat.id}>
                    <div className="flex justify-between mb-1">
                      <span className="text-gray-300">{cat.name}</span>
                      <span className="font-mono text-terminal-green">
                        {score.correct}/{score.total}
                      </span>
                    </div>
                    <div className="h-2 bg-dark-700 rounded-full">
                      <div
                        className="h-full bg-terminal-green rounded-full transition-all"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Question Review */}
          <div className="gradient-border rounded-lg bg-dark-800 p-6 mb-8">
            <h2 className="font-mono text-xl font-semibold text-terminal-cyan mb-6">// Question Review</h2>
            <div className="space-y-4">
              {shuffledQuestions.map((q, index) => {
                const userAnswer = answers[q.id];
                const isCorrect = userAnswer === q.correctIndex;

                return (
                  <details key={q.id} className="bg-dark-700 rounded-lg">
                    <summary className="px-4 py-3 cursor-pointer flex items-center gap-3">
                      <span className={`w-6 h-6 rounded-full flex items-center justify-center text-sm ${
                        isCorrect ? "bg-terminal-green/20 text-terminal-green" : "bg-red-500/20 text-red-400"
                      }`}>
                        {isCorrect ? "✓" : "✗"}
                      </span>
                      <span className="text-gray-300 flex-1">Q{index + 1}: {q.question.slice(0, 60)}...</span>
                    </summary>
                    <div className="px-4 pb-4 text-sm">
                      <p className="text-gray-400 mb-2">
                        <span className="text-gray-500">Your answer:</span>{" "}
                        <span className={isCorrect ? "text-terminal-green" : "text-red-400"}>
                          {userAnswer !== undefined ? q.options[userAnswer] : "Not answered"}
                        </span>
                      </p>
                      {!isCorrect && (
                        <p className="text-gray-400 mb-2">
                          <span className="text-gray-500">Correct answer:</span>{" "}
                          <span className="text-terminal-green">{q.options[q.correctIndex]}</span>
                        </p>
                      )}
                      <p className="text-gray-500 mt-2 italic">{q.explanation}</p>
                    </div>
                  </details>
                );
              })}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button
              onClick={() => window.print()}
              className="px-6 py-3 border border-terminal-green text-terminal-green font-semibold rounded-lg hover:bg-terminal-green/10 transition-colors"
            >
              Print Results
            </button>
            <a
              href="/screening"
              className="px-6 py-3 bg-terminal-green text-dark-900 font-semibold rounded-lg hover:bg-terminal-green/90 transition-colors text-center"
            >
              New Assessment
            </a>
          </div>

          {/* CTA */}
          <div className="mt-12 gradient-border rounded-lg bg-dark-800 p-8 text-center">
            <h3 className="text-xl font-bold mb-4">Need Help Building AI-Ready Teams?</h3>
            <p className="text-gray-400 mb-6">
              Get custom AI training programs tailored to your organization's needs.
            </p>
            <a
              href="/book"
              className="inline-block px-8 py-4 bg-terminal-green text-dark-900 font-bold rounded-lg hover:bg-terminal-green/90 transition-colors"
            >
              Book a Consultation
            </a>
          </div>
        </div>
      </main>
    );
  }

  return null;
}
